language: java
jdk: oraclejdk7

script:
  - ./gradlew build jacocoTestReport

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - skrzynecki.krzysztof@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle